### ISSUE TITLE
Build fails when DB is empty

### ISSUE THREAD

**Issue by movindugunarathna** [movindugunarathna/LandPulse#89]
```
Error: Failed to fetch posts!
    at l (/home/runner/work/LandPulse/LandPulse/.next/server/chunks/223.js:1:3072)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c (/home/runner/work/LandPulse/LandPulse/.next/server/app/page.js:1:7600)
    at s.findSort (/home/runner/work/LandPulse/LandPulse/.next/server/chunks/223.js:1:1568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (/home/runner/work/LandPulse/LandPulse/.next/server/chunks/223.js:1:2767)

> Export encountered errors on following paths:
	/page: /
    at async c (/home/runner/work/LandPulse/LandPulse/.next/server/app/page.js:1:7600)

```

**Comment by LuciferDIot** [comment]
Added post-checking condition before updating the UI. I think now the problem must be solved. But have to check it by testing manually.

**Comment by LuciferDIot** [comment]
Now its resolved
